extern ExitProcess
extern AllocConsole 
extern FreeConsole 
extern SetConsoleTitleA 
extern Sleep 
extern GetStdHandle
extern ReadFile
extern WriteFile
EXTERN MessageBoxA	

import ExitProcess		kernel32.dll
import AllocConsole		kernel32.dll 
import FreeConsole		kernel32.dll 
import SetConsoleTitleA	kernel32.dll 
import Sleep 			kernel32.dll
import GetStdHandle 	kernel32.dll
import ReadFile			kernel32.dll
import WriteFile		kernel32.dll
IMPORT MessageBoxA 		user32.dll